"""Shared context utilities for CLI commands."""

from pathlib import Path

import typer

from ash.cli.console import error
from ash.config import AshConfig, load_config

# Model options by provider (ordered by recommendation for cost/speed)
OPENAI_MODELS = [
    ("gpt-5.2", "GPT-5.2 (Recommended - flagship model)"),
    ("gpt-5.2", "GPT-5.2 (Balanced default)"),
    ("gpt-5.2-codex", "GPT-5.2 Codex (Optimized for coding)"),
]


def get_config(config_path: Path | None = None) -> AshConfig:
    """Load configuration with error handling.

    Args:
        config_path: Optional path to config file.

    Returns:
        Loaded AshConfig.

    Raises:
        typer.Exit: If configuration cannot be loaded.
    """
    try:
        return load_config(config_path)
    except FileNotFoundError:
        error("No configuration found. Run 'ash init' first.")
        raise typer.Exit(1) from None


def get_graph_dir() -> Path:
    """Get the graph directory for memory storage.

    Returns:
        Path to graph directory.
    """
    from ash.config.paths import get_graph_dir as _get_graph_dir

    return _get_graph_dir()


def generate_config_template() -> str:
    """Generate a config template with current recommended models.

    Returns:
        TOML config template string.
    """
    default_model = OPENAI_MODELS[0][0]  # gpt-5.2
    fast_model = OPENAI_MODELS[1][0]  # gpt-5.2
    codex_model = OPENAI_MODELS[2][0]  # gpt-5.2-codex

    return f'''# Ash Configuration
# Generated by: ash init
#
# Fill in your API key below, then run: ash upgrade

# =============================================================================
# API Key (required)
# =============================================================================
# Set here OR use environment variable: export OPENAI_API_KEY=sk-...

[openai]
api_key = ""

# =============================================================================
# Models
# =============================================================================
# GPT-5.2 as default, Fast for lightweight tasks, Codex for coding

[models.default]
provider = "openai"
model = "{default_model}"
temperature = 0.7
max_tokens = 4096

[models.fast]
provider = "openai"
# Suggested when available: gpt-5-mini (currently unsupported on openai-oauth)
model = "{fast_model}"
max_tokens = 4096

[models.codex]
provider = "openai"
model = "{codex_model}"
max_tokens = 8192

# =============================================================================
# Skill/Agent Overrides
# =============================================================================
# Override model for skills or agents

[skills.skill-writer]
model = "codex"  # Use coding model for skill creation

# =============================================================================
# Optional: Telegram Integration
# =============================================================================
# Get bot token from @BotFather, user ID from @userinfobot

# [telegram]
# bot_token = ""  # or set TELEGRAM_BOT_TOKEN env var
# allowed_users = ["123456789"]

# =============================================================================
# Optional: Web Search (Parallel)
# =============================================================================
# Get API key at: https://platform.parallel.ai/

# [parallel_search]
# api_key = ""  # or set PARALLEL_API_KEY env var

# =============================================================================
# Optional: External Capability Provider (skill-owned)
# =============================================================================
# Configure bundled google skill (provider bridge is auto-wired):
#
# [skills.google]
# enabled = true
#
# Registers an external capability bridge command (for example from a skill
# package/repo) that implements the capability provider contract.

# =============================================================================
# Optional: Semantic Search
# =============================================================================
# Requires OpenAI API key (same as above)

# [embeddings]
# provider = "openai"
# model = "text-embedding-3-small"
'''
